{% set python_min = '3.11' %}
{% set name = "pigeonxt-jupyter" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 012e832463bb9888f609159b51294d3aeeb94ce0d680d482c9fa3734c040f81c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - ipywidgets >=8.0.4,<9.0.0
    - jupyterlab >=3.5.2,<4.0.0
    - numpy >=1.24.1,<2.0.0
    - pandas >=1.5.2,<2.0.0
    - python >={{ python_min }},<4.0

test:
  imports:
    - pigeonXT
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dennisbakhuis/pigeonXT
  summary: PigeonXT is an extention to the original Pigeon; quickly annotate data in Jupyter notebooks.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
