{% set name = "pigeonxt-jupyter" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 83771fafdb168bf6cb282a01cf76052966d38267962573ed176877eae83f1bda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipywidgets
    - jupyterlab
    - numpy
    - pandas
    - python >=3.6

test:
  imports:
    - pigeonXT
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dennisbakhuis/pigeonXT
  summary: PigeonXT is an extention to the original Pigeon; quickly annotate data in Jupyter notebooks.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
